### ISSUE TITLE
Delayed responses when using Couchbase

### ISSUE THREAD

**Issue by Cmdv** [quasar-analytics/quasar#2326]
When mounting and using Couchbase response times are high.

### Reproduction guide:
In this example the data has only 7 rows.

- When mounting Couchbase everything is of normal speed and you are presented with root folders.
- Click on a folder who's content has data. Those files can take 4-5secs to display _(#1830 could be a solution to this)_
- Click on file, should create a workspace with `Preview Card` being shown. It takes around 4secs to leave filesystem then another 20secs of the load spinner.

### Observed behaviour:
It seems that the time is being spent on XHR calls, I assume it is either quasar or Couchbase which might be causing the slow responses.

click [here](https://user-images.githubusercontent.com/3036557/27137191-2f37dd3a-5115-11e7-8d3e-c8a44ee85710.gif) to view large version _(the gif conversion slowed down the frame rate but you can see recorded times in the dev tools panel)_
![couchbase](https://user-images.githubusercontent.com/3036557/27137191-2f37dd3a-5115-11e7-8d3e-c8a44ee85710.gif)

**Comment by beckyconning** [comment]
So so glad to be seeing these tickets coming from frontend usage. Thanks for working on this @Cmdv!

**Comment by drostron** [comment]
@Cmdv How many documents are in the associated bucket? Do you have the recommended index on the type field as recommended?

**Comment by drostron** [comment]
To clarify, if you're on a version before the `docTypeKey` mount configuration addition you'll want an index on the type field, otherwise you'll want an index on whatever `docTypeKey` is configured to be as recommended [here](https://github.com/quasar-analytics/quasar#couchbase).

**Comment by Cmdv** [comment]
@drostron [this](https://github.com/Cmdv/slamdata/blob/add-tests-for-databases/docker/scripts/initMarklogic#L39-L61) is how I set up the db and yes all the data has a `type field`
```
{
  "type": "simple",
  "status": "ACTIVE",
  "name": "foo"
}
```

**Comment by Cmdv** [comment]
@drostron my bad I was referring to Marklogic there [here](https://github.com/Cmdv/slamdata/blob/add-tests-for-databases/docker/scripts/initCouchbase) is how I set up the db but I don't think it uses any `docTypeKey`

**Comment by drostron** [comment]
@Cmdv Ok, looking at `initCouchbase` looks like there isn't a secondary index on type. Assuming there are quite a few documents in the `testDb` bucket, you'll want to create one as [here](https://github.com/quasar-analytics/quasar/blob/master/docker/scripts/initCouchbase#L49).

**Comment by drostron** [comment]
The curl command to do so in your script would be like:
```
curl -v $CB:8093/query/service -d 'statement=CREATE INDEX `testdb_type_idx ` ON `testDb`(type)'
```

**Comment by Cmdv** [comment]
Going to close this as doing the secondary Indexing as recommended by @drostron did the trick and reduced times significantly.

displaying files:       `5 s` -> `1.52 s`
table card of data:  `20 s` -> `4 s`

Thanks 👍

**Comment by jdegoes** [comment]
2 - 4 seconds is still significant. If it's much more than MongoDB, we should leave it open.

**Comment by Cmdv** [comment]
@jdegoes I'll do some comparisons and report back

**Comment by Cmdv** [comment]
So after making a comparison here are the results. I've taken the times of the XHR requests that took the longest. Both were tested on identical docker containers.

### Couchbase:
1. show files:               `1.31 s`
2. leave FileSystem:   `1.29 s`
3. display table card:  `1.49 s`

### MongoDB:
1. show files:               `26 ms`
2. leave FileSystem:   `39 ms`
3. display table card:  `71 ms`

### URLS:
1. `/metadata/fs/testDb/`
2. `/metadata/fs/testDb/`
3. `/query/fs/testDb/?q=SELECT%20COUNT(*)%20AS%20total%20FROM%20%60%2FtestDb%2Fsimple%60`

@jdegoes they do differ quite a bit, do you think Couchbase and MongoDB are expected to run on an even keel?

I'll reopen as suggested. 😄

**Comment by drostron** [comment]
@nicflores and I collected some rough timings related to directory listing after loading @Cmdv's test data (62,424 documents).

A request to quasar for `/metadata/fs/cb/testDb/` takes about 1.4 secs. The corresponding generated N1QL query ```select distinct `type` from testDb where type like "%"``` takes about 1.2 secs when issued in CB's web console. The like operator arrises from the general handling of quasar filesystem paths via the type field. We also tested without the where clause but that doesn't leverage the index on type and took about 6 seconds.

Due to memory optimized indexes and a secondary index on the type field being in place the simple DB tuning has been addressed. A CB expert might have something further to offer.

As an alternative approach, incremental views might hold promise for a more performant directory listing. We'll take a look and report back.

**Comment by drostron** [comment]
We found when using a view we could get sub 1/10 s queries for directory listings. Further we looked into query 3. and determined that `QueryFile.convertToQScriptRead`'s use of the same slow list contents query contributed the majority of the time spent for that query.

Making this change shouldn't take too much effort and should yield a noticeable speedup.

**Comment by drostron** [comment]
@Cmdv I took a few timings against [18.7.0](https://github.com/quasar-analytics/quasar/releases/tag/v18.7.0) with the new view based list contents. Looks like Couchbase is now on par with MongoDB for the endpoints you listed.

### Couchbase
1. show files:               `30 ms`
2. leave FileSystem:   `30 ms`
3. display table card:  `80 ms`

Please confirm. Thanks.

**Comment by Cmdv** [comment]
@drostron wicked, I'll up the version of Quasar and test and report back 👍

**Comment by Cmdv** [comment]
@drostron speeds seem greatly improved. 

I'm still getting some delay of files showing on the very first mount of the database. Think once things are in the metadata store then the response time is fine.

not 100% if this is docker related though can't really tell.

**Comment by drostron** [comment]
@Cmdv Glad you are seeing improved response times.

A few indexes are now created upon mount, if not pre-existing. I'd expect a slight delay until those are finished building. Afterwards response times should be close to the times listed above. Sounds like this is what you're experiencing.

**Comment by Cmdv** [comment]
@drostron think you are right and that's why I see them in the tests as they run as a brand new mount. I'll close this because think the speed issues have been fixed 😸
